[connections.snowflake]
account = "IIWIBLX-SYB71355"
user = "hongwuz5"
password = "GuoguoGuoguo@1"
role = "SYSADMIN"
warehouse = "compute_wh"
database = "smoothies"
schema = "public"
client_session_keep_alive = true