[connections.snowflake]
account = "IIWIBLX-SYB71355"
user = "mellymel"
password ="eyJraWQiOiI3MDM4MzY0NzcxNjc2MTc4IiwiYWxnIjoiRVMyNTYifQ.eyJwIjoiNDE5NTE5MzE2OjQxOTUxOTM2NCIsImlzcyI6IlNGOjEwNDkiLCJleHAiOjE4MDEyMDEwOTl9.hXahYoICZDJbLp4mCE7-kjKFKglt0zvPl9xadfPBT4Onk5XHiiobeFttBUgDLgo8oI3pHhYxz-fApYFs4beAzw"
role = "SYSADMIN"
warehouse = "compute_wh"
database = "smoothies"
schema = "public"
client_session_keep_alive = true
